version: '3.3'
services:
  proxy:
    container_name: proxy
    image: shroomlife/docker-proxy:latest
    ports:
      - "80:80"
      - "443:443"
  example.com:
    container_name: example.com.proxy
    image: httpd:latest
