version: '3.3'
services:
  proxy:
    container_name: proxy
    image: shroomlife/docker-proxy:latest
    build: .
    ports:
      - "80:80"
      - "443:443"
  example1:
    container_name: localhost.proxy
    image: httpd:latest
  example2:
    container_name: localshroom.proxy
    image: wordpress:latest
