name: Deployment Workflow

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: install
      run: yarn install
    - name: test
      run: yarn test
    - name: docker build
      run: docker build . --tag shroomlife/docker-https-proxy:latest
    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: docker push
      run: docker push shroomlife/docker-https-proxy:latest
