name: docker-push

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Install Dependencies
      run: yarn install
    - name: Start Test with Jest
      run: yarn test
    - name: Build Docker Image shroomlife/docker-https-proxy:latest
      run: docker build . --tag shroomlife/docker-https-proxy:latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker Image to Hub
      run: docker push shroomlife/docker-https-proxy:latest
